//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using Common.Paginations.Models;
using Common;
using DataTransferObjects.Courses;
using Gamification.Domain.Entities;

namespace Services.Courses
{
    public interface ICoursesService
    {
        Task<CourseViewModel> AddAsync(CourseCreationDto courseCreationDto);
        Task<List<CourseViewModel>> GetAllAsync();
        Task<ListResult<CourseViewModel>> FilterAsync(PaginationOptions filter);
        Task<CourseViewModel> GetByIdAsync(int id);
        Task<CourseViewModel> UpdateAsync(int id, CourseModificationDto courseModificationDto);
        Task<CourseViewModel> DeleteAsync(int id);
    }
}