//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using Common.Paginations.Models;
using Common;
using Gamification.Domain.Entities;

namespace Services.Questions
{
    public interface IQuestionsService
    {
        Task<Question> AddAsync(Question question);
        Task<List<Question>> GetAllAsync();
        Task<ListResult<Question>> FilterAsync(PaginationOptions filter);
        Task<Question> GetByIdAsync(int id);
        Task<Question> UpdateAsync(int id, Question question);
        Task<Question> DeleteAsync(int id);
    }
}