//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using Common.Paginations.Models;
using Common;
using DataTransferObjects.Questions;
using Gamification.Domain.Entities;

namespace Services.Questions
{
    public interface IQuestionsService
    {
        Task<QuestionViewModel> AddAsync(QuestionCreationDto questionCreationDto);
        Task<List<QuestionViewModel>> GetAllAsync();
        Task<List<QuestionViewModel>> GetAllByTestAsync(int testId);
        Task<ListResult<QuestionViewModel>> FilterAsync(PaginationOptions filter);
        Task<QuestionViewModel> GetByIdAsync(int id);
        Task<QuestionViewModel> UpdateAsync(int id, QuestionModificationDto questionModificationDto);
        Task<QuestionViewModel> DeleteAsync(int id);
    }
}