//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using AutoMapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Common.Paginations.Models;
using Common.Paginations.Extensions;
using Common.ServiceAttribute;
using Common;
using DataTransferObjects.Answers;
using Gamification.Infrastructure;
using Gamification.Domain.Entities;

namespace Services.Answers
{
    [ScopedService]
    public class AnswersService : IAnswersService
    {
        private readonly GamificationDb _gamificationDb;
        private readonly IMapper _mapper;
        public AnswersService(GamificationDb gamificationDb, IMapper mapper)
        {
            _gamificationDb = gamificationDb;
            _mapper = mapper;
        }

        public async Task<AnswerViewModel> AddAsync(AnswerCreationDto answerCreationDto)
        {
            var entity = _mapper.Map<Answer>(answerCreationDto);
            var entry = await _gamificationDb.Set<Answer>().AddAsync(entity);
            await _gamificationDb.SaveChangesAsync();
            return _mapper.Map<AnswerViewModel>(entry.Entity);
        }

        public async Task<List<AnswerViewModel>> GetAllAsync()
        {
            var entities = await _gamificationDb.Set<Answer>().ToListAsync();
            return _mapper.Map<List<AnswerViewModel>>(entities);
        }

        public async Task<ListResult<AnswerViewModel>> FilterAsync(PaginationOptions filter)
        {
            var paginatedResult = await _gamificationDb.Set<Answer>().ApplyPaginationAsync(filter);
            var Answers = _mapper.Map<List<AnswerViewModel>>(paginatedResult.paginatedList);
            return new ListResult<AnswerViewModel>(paginatedResult.paginationMetadata, Answers);
        }

        public async Task<AnswerViewModel> GetByIdAsync(int id)
        {
            var entity = await _gamificationDb.Set<Answer>().FirstOrDefaultAsync(x => x.Id == id);
            if (entity == null)
                throw new InvalidOperationException($"Answer with Id {id} not found.");
            return _mapper.Map<AnswerViewModel>(entity);
        }

        public async Task<AnswerViewModel> UpdateAsync(int id, AnswerModificationDto answerModificationDto)
        {
            var entity = await _gamificationDb.Set<Answer>().FirstOrDefaultAsync(x => x.Id == id);
            if (entity == null)
                throw new InvalidOperationException($"Answer with {id} not found.");
            _mapper.Map(answerModificationDto, entity);
            var entry = _gamificationDb.Set<Answer>().Update(entity);
            await _gamificationDb.SaveChangesAsync();
            return _mapper.Map<AnswerViewModel>(entry.Entity);
        }

        public async Task<AnswerViewModel> DeleteAsync(int id)
        {
            var entity = await _gamificationDb.Set<Answer>().FirstOrDefaultAsync(x => x.Id == id);
            if (entity == null)
                throw new InvalidOperationException($"Answer with {id} not found.");
            var entry = _gamificationDb.Set<Answer>().Remove(entity);
            await _gamificationDb.SaveChangesAsync();
            return _mapper.Map<AnswerViewModel>(entry.Entity);
        }
    }

    /// <summary>
    /// AutoMapper mapping profile for Answer entity.
    /// </summary>
    public class AnswerMappingProfile : Profile
    {
        public AnswerMappingProfile()
        {
            CreateMap<Answer, AnswerViewModel>();
            CreateMap<AnswerCreationDto, Answer>();
            CreateMap<AnswerModificationDto, Answer>();
        }
    }
}