//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using Common.Paginations.Models;
using Common;
using DataTransferObjects.Answers;
using Gamification.Domain.Entities;

namespace Services.Answers
{
    public interface IAnswersService
    {
        Task<AnswerViewModel> AddAsync(AnswerCreationDto answerCreationDto);
        Task<List<AnswerViewModel>> GetAllAsync();
        Task<ListResult<AnswerViewModel>> FilterAsync(PaginationOptions filter);
        Task<AnswerViewModel> GetByIdAsync(int id);
        Task<AnswerViewModel> UpdateAsync(int id, AnswerModificationDto answerModificationDto);
        Task<AnswerViewModel> DeleteAsync(int id);
    }
}