//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using Gamification.Domain.Entities;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace DataTransferObjects.Questions;

public class QuestionViewModel
{
    [JsonPropertyName("text")]
    public string Text { get; set; }
    [JsonPropertyName("testId")]
    public int TestId { get; set; }
    [JsonPropertyName("test")]
    public Test Test { get; set; }
    [JsonPropertyName("answers")]
    public List<Answer> Answers { get; set; }
    [JsonPropertyName("createdBy")]
    public string CreatedBy { get; set; }
    [JsonPropertyName("created")]
    public DateTime? Created { get; set; }
    [JsonPropertyName("lastModifiedBy")]
    public string LastModifiedBy { get; set; }
    [JsonPropertyName("lastModified")]
    public DateTime? LastModified { get; set; }
    [JsonPropertyName("id")]
    public int Id { get; set; }
}
