//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using Gamification.Domain.Entities;

namespace DataTransferObjects.Courses;

public class CourseViewModel
{
    public string Title { get; set; }
    public string Description { get; set; }
    public float Duration { get; set; }
    public DateTime StartTime { get; set; }
    public DateTime StartDate { get; set; }
    public string CreatedBy { get; set; }
    public DateTime? Created { get; set; }
    public string LastModifiedBy { get; set; }
    public DateTime? LastModified { get; set; }
    public int Id { get; set; }
}
