//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using Gamification.Domain.Entities;

namespace DataTransferObjects.Tests;

public class TestCreationDto
{
	public string Title { get; set; }
	public string Description { get; set; }
	public float Duration { get; set; }
	public TestStatus Status { get; set; }
}
