//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using System;
using Gamification.Domain.Entities;

namespace DataTransferObjects.Answers;

public class AnswerViewModel
{
    public int Id { get; set; }
    public string Text { get; set; }
    public int QuestionId { get; set; }
    public Question Question { get; set; }
    public string CreatedBy { get; set; }
    public DateTime? Created { get; set; }
}