//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using AutoMapper;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using Common.Paginations.Models;
using Common.Paginations.Extensions;
using Common.ServiceAttribute;
using Common;
using DataTransferObjects.Tests;
using Gamification.Infrastructure;
using Gamification.Domain.Entities;

namespace Services.Tests
{
    [ScopedService]
    public class TestsService : ITestsService
    {
        private readonly GamificationDb _gamificationDb;
        private readonly IMapper _mapper;
        public TestsService(GamificationDb gamificationDb, IMapper mapper)
        {
            _gamificationDb = gamificationDb;
            _mapper = mapper;
        }

        public async Task<TestViewModel> AddAsync(TestCreationDto testCreationDto)
        {
            var entity = _mapper.Map<Test>(testCreationDto);
            var entry = await _gamificationDb.Set<Test>().AddAsync(entity);
            await _gamificationDb.SaveChangesAsync();
            return _mapper.Map<TestViewModel>(entry.Entity);
        }

        public async Task<List<TestViewModel>> GetAllAsync()
        {
            var entities = await _gamificationDb.Set<Test>().ToListAsync();
            return _mapper.Map<List<TestViewModel>>(entities);
        }

        public async Task<ListResult<TestViewModel>> FilterAsync(PaginationOptions filter)
        {
            var paginatedResult = await _gamificationDb.Set<Test>().ApplyPaginationAsync(filter);
            var Tests = _mapper.Map<List<TestViewModel>>(paginatedResult.paginatedList);
            return new ListResult<TestViewModel>(paginatedResult.paginationMetadata, Tests);
        }

        public async Task<TestViewModel> GetByIdAsync(int id)
        {
            var entity = await _gamificationDb.Set<Test>().FirstOrDefaultAsync(x => x.Id == id);
            if (entity == null)
                throw new InvalidOperationException($"Test with Id {id} not found.");
            return _mapper.Map<TestViewModel>(entity);
        }

        public async Task<TestViewModel> UpdateAsync(int id, TestModificationDto testModificationDto)
        {
            var entity = await _gamificationDb.Set<Test>().FirstOrDefaultAsync(x => x.Id == id);
            if (entity == null)
                throw new InvalidOperationException($"Test with {id} not found.");
            _mapper.Map(testModificationDto, entity);
            var entry = _gamificationDb.Set<Test>().Update(entity);
            await _gamificationDb.SaveChangesAsync();
            return _mapper.Map<TestViewModel>(entry.Entity);
        }

        public async Task<TestViewModel> DeleteAsync(int id)
        {
            var entity = await _gamificationDb.Set<Test>().FirstOrDefaultAsync(x => x.Id == id);
            if (entity == null)
                throw new InvalidOperationException($"Test with {id} not found.");
            var entry = _gamificationDb.Set<Test>().Remove(entity);
            await _gamificationDb.SaveChangesAsync();
            return _mapper.Map<TestViewModel>(entry.Entity);
        }
    }

    /// <summary>
    /// AutoMapper mapping profile for Test entity.
    /// </summary>
    public class TestMappingProfile : Profile
    {
        public TestMappingProfile()
        {
            CreateMap<Test, TestViewModel>();
            CreateMap<TestCreationDto, Test>();
            CreateMap<TestModificationDto, Test>();
        }
    }
}