//-----------------------------------------------------------------------
// This file is autogenerated by EntityCore
// <auto-generated />
//-----------------------------------------------------------------------

using Common.Paginations.Models;
using Common;
using DataTransferObjects.Lessons;
using Gamification.Domain.Entities;

namespace Services.Lessons
{
    public interface ILessonsService
    {
        Task<LessonViewModel> AddAsync(LessonCreationDto lessonCreationDto);
        Task<List<LessonViewModel>> GetAllAsync();
        Task<ListResult<LessonViewModel>> FilterAsync(PaginationOptions filter);
        Task<LessonViewModel> GetByIdAsync(int id);
        Task<LessonViewModel> UpdateAsync(int id, LessonModificationDto lessonModificationDto);
        Task<LessonViewModel> DeleteAsync(int id);
    }
}